variable "env" {}
variable "tags" {}
variable "default_vpc_id" {}
variable "default_route_table" {}
variable "vpc" {}
variable "docdb" {}
variable "rds" {}
variable "elasticcache" {}
variable "rabbitmq" {}
variable "alb" {}
variable "apps" {}
variable "bastion_cidr" {}
variable "dns_domain" {}